Repository Tow-Boot/Tow-Boot, pull requests merged in 2022-11, with the labels that each got.

#178 U-Boot: 2021.10 → 2022.07
  boards/libreComputer-amlS805xAc/default.nix
  boards/libreComputer-rocRk3399Pc/0001-roc-pc-rk3399-Apply-USB-fixes.patch
  boards/libreComputer-rocRk3399Pc/default.nix
  boards/libreComputer-rocRk3399Pc/roc-pc-config.patch
  boards/odroid-C2/default.nix
  boards/pine64-pineA64LTS/0001-configs-pine64-lts-Enable-SPI-flash.patch
  boards/pine64-pineA64LTS/default.nix
  boards/pine64-pinebookPro/0001-arch-arm-dts-Sync-rk3399-pinebook-pro-with-Linux.patch
  boards/pine64-pinebookPro/0001-rk3399-light-pinebook-power-and-standby-leds-during-.patch
  boards/pine64-pinebookPro/default.nix
  boards/pine64-pinephoneA64/default.nix
  boards/pine64-pinephonePro/0001-adc-rockchip-saradc-Implement-reference-voltage.patch
  boards/pine64-pinephonePro/0001-pine64-pinephonepro-device-enablement.patch
  boards/pine64-pinephonePro/0001-rk8xx-poweroff-support.patch
  boards/pine64-pinephonePro/default.nix
  boards/radxa-RockPi4/0001-rockpi4-rk3399-add-spi-support.patch
  boards/radxa-RockPi4/general-add-xtx-spi-nor-chips.patch
  boards/radxa-zero2/0001-arch-arm-dts-Sync-amlogic-meson-DT-with-mainline.patch
  boards/radxa-zero2/0001-radxa-zero2-board-enablement.patch
  boards/radxa-zero2/default.nix
  boards/raspberryPi-aarch64/0001-Tow-Boot-rpi-Increase-malloc-pool-up-to-64MiB-env.patch
  boards/raspberryPi-aarch64/0001-configs-rpi-allow-for-bigger-kernels.patch
  boards/raspberryPi-aarch64/default.nix
  boards/uBoot-sandbox/0001-sandbox-Force-window-size.patch
  boards/uBoot-sandbox/default.nix
  modules/default.nix
  modules/hardware/allwinner/default.nix
  modules/hardware/rockchip/0001-BACKPORT-power-pmic-rk8xx-Workaround-pmic-failure-wh.patch
  modules/hardware/rockchip/default.nix
  modules/tow-boot/builder.nix
  modules/tow-boot/config.nix
  modules/tow-boot/installer.nix
  modules/tow-boot/src.nix
  support/overlay/overlay.nix
  support/u-boot/2022.07/patches/0001-HACK-video-sync-dirty.patch
  support/u-boot/2022.07/patches/0001-Provide-opinionated-boot-flow.patch
  support/u-boot/2022.07/patches/0001-Revert-rockchip-Fix-MMC-boot-order.patch
  support/u-boot/2022.07/patches/0001-autoboot-Prevent-C-from-affecting-menucmd.patch
  support/u-boot/2022.07/patches/0001-autoboot-show-menu-only-on-menu-key.patch
  support/u-boot/2022.07/patches/0001-bootmenu-improvements.patch
  support/u-boot/2022.07/patches/0001-cmd-Add-pause-command.patch
  support/u-boot/2022.07/patches/0001-drivers-video-Add-dependency-on-GZIP.patch
  support/u-boot/2022.07/patches/0001-meson-Prefer-internal-boot-methods-first.patch
  support/u-boot/2022.07/patches/0001-pdcurses.patch
  support/u-boot/2022.07/patches/0001-splash-improvements.patch
  support/u-boot/2022.07/patches/0001-sunxi-Predictable-boot-order.patch
  support/u-boot/2022.07/patches/0001-sunxi-Prefer-SD-for-operating-system-boot.patch
  support/u-boot/2022.07/patches/0001-sunxi-Use-mmc_get_env_dev-only-if-relevant.patch
  support/u-boot/2022.07/patches/0001-tow-boot-menu.patch
  support/u-boot/2022.07/patches/0001-treewide-Identify-as-Tow-Boot.patch
Labels: type: task

#206 u-boot/patches: Identify as Tow-Boot in TPL/SPL, SMBIOS, and drop date
  support/u-boot/2022.07/patches/0001-treewide-Identify-as-Tow-Boot.patch
Labels: type: enhancement

#207 u-boot/patches: Add more correct chassis information in SMBIOS
  modules/tow-boot/src.nix
  support/u-boot/2022.07/patches/0001-smbios-enclosure-support.patch
Labels: type: enhancement

#210 2022.07/patches: Fix smbios chassis-type handling when missing
  support/u-boot/2022.07/patches/0001-smbios-enclosure-support.patch
Labels: type: bug

#211 pine64-pinephonePro: Perform PMIC setup on boot
  boards/pine64-pinephonePro/default.nix
Labels: family: rockchip

#208 radxa-RockPi4: Enable USB support at boot
  boards/radxa-RockPi4/default.nix
Labels: help wanted, family: rockchip, type: fix

#194 i2c: rockchip: De-initialize the bus after start bit failure
  boards/pine64-pinephonePro/default.nix
Labels: family: rockchip

#195 Pinephone Pro: Set GPIO4_PD3 as input
  boards/pine64-pinephonePro/0001-rk_gpio-Added-spl_gpio_input-method.patch
  boards/pine64-pinephonePro/0009-Pinephone-Pro-Set-GPIO4_PD3-as-input.patch
  boards/pine64-pinephonePro/default.nix
Labels: family: rockchip

#130 Update README.md
  boards/pine64-pinephoneA64/README.md
Labels: topic: documentation
