Repository Tow-Boot/Tow-Boot, pull requests merged in 2022-06, with the labels that each got.

#158 Add smbios for all
  modules/tow-boot/default.nix
  modules/tow-boot/smbios.nix
Labels: type: enhancement

#135 pine64-pinephonePro: add smbios data
  boards/pine64-pinephonePro/0001-rk3399-pinephone-pro-add-smbios-info.patch
  boards/pine64-pinephonePro/default.nix
Labels: type: enhancement

#149 odroid-N2: Add support for XT25Q64D
  boards/odroid-N2/0002-Add-support-for-XTX-SPI-XT25Q64D.patch
  boards/odroid-N2/default.nix
Labels: type: fix

#146 doc/getting-started: ask to grow the GPT partition to physical size
  doc/getting-started.md
Labels: topic: documentation
