Repository Tow-Boot/Tow-Boot, pull requests merged in 2023-07, with the labels that each got.

#182 Improved documentation when using serial
  doc/development-guide.md
  doc/getting-started.md
  doc/serial.md
Labels: topic: documentation

#243 doc: Make device cross-linking work
  boards/radxa-RockPi4C/README.md
  doc/_support/converter/main.rb
Labels: topic: documentation

#201 Configure GitHub Actions for building images
  .ci/devices-list.nix
  .github/workflows/ci.yml
  boards/raspberryPi-aarch64/default.nix
  doc/default.nix
  modules/build.nix
  modules/tow-boot/builder.nix
Labels: topic: CI/CD

#253 nixpkgs: Update to July 8th nixos-unstable channel
  boards/olimex-teresI/default.nix
  boards/raspberryPi-aarch64/default.nix
  doc/_support/devices/default.nix
  doc/_support/styles/default.nix
  doc/default.nix
  modules/build.nix
  modules/tow-boot/builder.nix
  nixpkgs.nix
  release.nix
  support/image-builder/disk-image/partitioning-scheme/gpt/builder.nix
  support/image-builder/disk-image/partitioning-scheme/mbr/builder.nix
  support/nix/eval-kconfig.nix
  support/nix/eval-with-configuration.nix
  support/overlay/arm-trusted-firmware/default.nix
  support/overlay/crust-firmware/default.nix
  support/overlay/overlay.nix
Labels: type: update

#252 Add stock U-Boot refs up to 2023.07
  modules/tow-boot/builder.nix
  modules/tow-boot/config.nix
  modules/tow-boot/options.nix
  modules/tow-boot/src.nix
  modules/u-boot.nix
  support/check-all-stock-uboot.nix
Labels: type: update
