Repository Tow-Boot/Tow-Boot, pull requests merged in 2023-10, with the labels that each got.

#229 Add support for OrangePi PC2
  boards/orangePi-pc2/default.nix
Labels: 1. family: allwinner, 4. type: new port, 0. priority: normal

#213 libreComputer-amlS905xCc: Add support for AML-S905X-CC (Le Potato)
  boards/libreComputer-amlS905xCc/default.nix
  modules/hardware/amlogic/default.nix
Labels: 1. family: amlogic, 4. type: new port, 0. priority: normal

#256 Add support for Libre Computer ALL-H3-CC H5
  boards/libreComputer-allH3CcH5/default.nix
Labels: 1. family: allwinner, 4. type: new port, 0. priority: normal

#257 Add support for FriendlyELEC NanoPi M1
  boards/friendlyElec-nanoPiM1/default.nix
Labels: 1. family: allwinner, 4. type: new port, 0. priority: normal

#267 Add support level to device descriptions
  boards/friendlyElec-nanoPiM1/default.nix
  boards/libreComputer-allH3CcH5/default.nix
  boards/libreComputer-amlS805xAc/default.nix
  boards/libreComputer-amlS905xCc/default.nix
  boards/libreComputer-rocRk3399Pc/default.nix
  boards/odroid-C2/default.nix
  boards/odroid-C4/default.nix
  boards/odroid-N2/default.nix
  boards/olimex-teresI/default.nix
  boards/orangePi-pc/default.nix
  boards/orangePi-pc2/default.nix
  boards/orangePi-zeroPlus2H5/default.nix
  boards/pine64-pineA64/default.nix
  boards/pine64-pineA64LTS/default.nix
  boards/pine64-pinebookA64/default.nix
  boards/pine64-pinebookPro/default.nix
  boards/pine64-pinephoneA64/default.nix
  boards/pine64-pinephonePro/default.nix
  boards/pine64-rockpro64/default.nix
  boards/radxa-RockPi4/default.nix
  boards/radxa-zero2/default.nix
  boards/raspberryPi-aarch64/default.nix
  boards/uBoot-sandbox/default.nix
  doc/_support/devices/generate-devices-listing.rb
  modules/device.nix
  modules/documentation.nix
  modules/metadata.nix
Labels: 4. type: documentation, 0. priority: high

#274 Mark 007-rc2
  modules/tow-boot/identity.nix
  modules/tow-boot/src.nix
Labels: 1. family: amlogic, 0. priority: high

#276 Add mmcboot installer for ODROID-C4
  boards/odroid-C4/default.nix
Labels: 4. type: enhancement, 0. priority: normal

#275 Add support for FriendlyElec NanoPi M1 Plus
  boards/friendlyElec-nanoPiM1Plus/default.nix
Labels: 1. family: allwinner, 4. type: new port, 0. priority: normal

#270 Tag output with uSWIDs
  modules/tow-boot/builder.nix
  modules/tow-boot/config.nix
  modules/tow-boot/default.nix
  modules/tow-boot/options.nix
  modules/tow-boot/uswid.nix
  release.nix
  support/overlay/overlay.nix
  support/overlay/uswid/default.nix
Labels: 4. type: task, 0. priority: high

#277 rockchip: Use the "new" sysreset poweroff implementation
  modules/hardware/rockchip/default.nix
  modules/tow-boot/identity.nix
  modules/tow-boot/src.nix
Labels: 1. family: rockchip, 0. priority: normal, 4. type: cleanup

#282 libreComputer-allH3CcH5: Fix identifier
  boards/libreComputer-allH3CcH5/default.nix
Labels: 4. type: bug, 0. priority: normal
