Repository Tow-Boot/Tow-Boot, pull requests merged in 2024-04, with the labels that each got.

#280 Tow-Boot: update to -rc4 (rockchip + pinephonePro)
  boards/pine64-pinephonePro/default.nix
  modules/tow-boot/identity.nix
  modules/tow-boot/src.nix
Labels: 4. type: bug, 1. family: rockchip, 0. priority: normal

#291 arm-trusted-firmware: 2.9 -> 2.10
  support/overlay/arm-trusted-firmware/default.nix
Labels: 4. type: update, 0. priority: high

#294 crust-firmware: untagged-2023-02-28 -> 0.6
  support/overlay/crust-firmware/default.nix
Labels: 1. family: allwinner, 4. type: update, 0. priority: normal

#296 Add support for FriendlyElec NanoPi R4S
  boards/friendlyElec-nanoPiR4S/default.nix
Labels: 1. family: rockchip, 4. type: new port, 0. priority: normal

#310 tow-boot/builder: pass config validation as a package
  modules/tow-boot/builder.nix
  support/nix/eval-kconfig.nix
Labels: 0. priority: normal, 4. type: cleanup

#311 tow-boot/builder: Drop platform-specific hacks and cleanup + unify baud rate
  modules/tow-boot/builder.nix
  modules/tow-boot/config.nix
Labels: 0. priority: normal, 4. type: cleanup

#290 modules/tow-boot: Fix missing bootdelay argument in AUTOBOOT_PROMPT
  modules/tow-boot/config.nix
Labels: 4. type: fix, 0. priority: normal

#313 Improve generic U-Boot support
  boards/uBoot-sandbox/default.nix
  modules/build.nix
  modules/tow-boot/builder.nix
  modules/tow-boot/phone-ux.nix
  modules/tow-boot/src.nix
  support/nix/eval-kconfig.nix
Labels: 0. priority: normal, 4. type: cleanup
